services:
    dyosis.util.abstract_container_aware:
        abstract: true
        calls:
        - [setContainer, ['@service_container']]

    dyosis.util.case_manager:
        class: Dyosis\CRUDBundle\Service\Util\CaseManager
        public: true